autocommit on change

diff --git a/gcc/PKGBUILD b/gcc/PKGBUILD
--- a/gcc/PKGBUILD
+++ b/gcc/PKGBUILD
@@ -38,6 +38,9 @@ source=(ftp://gcc.gnu.org/pub/gcc/snapshots/LATEST-9/gcc-${_majorver}-${_snapsho
         0001-Ignore-Werror-if-GCC_IGNORE_WERROR-environment-varia.patch
         0001-Always-use-z-now-when-linking-with-pie.patch
         icelake.patch
+        gcc-allow-newer-autoconf.patch
+        gcc-4.8.2-disable_multilib_i386_linux64.patch
+        0018-isl-0.20.patch
         zero-regs-gcc8.patch)
 validpgpkeys=(F3691687D867B81B51CE07D9BBE43771487328A9  # bpiotrowski@archlinux.org
               86CFFCA918CF3AF47147588051E8B148A9999C34  # evangelos@foutrelis.com
@@ -75,8 +78,12 @@ prepare() {
   [[ ! -d gcc ]] && ln -s gcc-${_majorver}-${_snapshot} gcc
   cd gcc
 
-  patch -p1 -i "$srcdir/010-documentation.patch"
-  patch -p1 -i "$srcdir/zero-regs-gcc8.patch"
+#  patch -p1 -i "$srcdir/010-documentation.patch"
+#  patch -p1 -i "$srcdir/zero-regs-gcc8.patch"
+  patch -p1 -i "$srcdir/0018-isl-0.20.patch"
+  patch -p1 -i "$srcdir/gcc-allow-newer-autoconf.patch"
+  patch -p1 -i "$srcdir/gcc-4.8.2-disable_multilib_i386_linux64.patch"
+
 
   # link isl for in-tree build
   ln -s ../isl-${_islver} isl
@@ -101,6 +108,9 @@ build() {
   CFLAGS=${CFLAGS/-pipe/}
   CXXFLAGS=${CXXFLAGS/-pipe/}
 
+  export CC='ccache gcc'
+  export CXX='ccache g++'
+
   "$srcdir/gcc/configure" --prefix=/usr \
       --libdir=/usr/lib \
       --libexecdir=/usr/lib \
@@ -124,16 +134,25 @@ build() {
       --enable-install-libiberty \
       --with-linker-hash-style=gnu \
       --enable-gnu-indirect-function \
-      --disable-multilib \
+      --enable-multilib \
       --disable-werror \
       --enable-checking=release \
+      --disable-libmpx \
       --with-tune=haswell \
       --with-arch=haswell \
       --with-diagnostics-color=always \
-      --with-headers=/usr/include
-      --enable-cet=no
+      --with-headers=/usr/include \
+      --enable-cet=auto
 
-  noti make
+  noti nice -n 19 make V=1 all
+}
+
+check() {
+  cd gcc-build
+
+  # do not abort on error as some are "expected"
+  make -k check || true
+  "$srcdir/gcc/contrib/test_summary"
 }
 
 package_gcc-libs() {
@@ -198,7 +217,6 @@ package_gcc() {
   mv "$pkgdir"/usr/lib/libstdc++.so.6.*-gdb.py \
     "$pkgdir/usr/share/gdb/auto-load/usr/lib/"
   rm "$pkgdir"/usr/lib/libstdc++.so*
-  rm "$pkgdir"/usr/lib/libstdc++.a
 
   make DESTDIR="$pkgdir" install-fixincludes
   make -C gcc DESTDIR="$pkgdir" install-mkheaders
